-- Insert default brands into the brands table
-- These are commonly known fashion and clothing brands

INSERT INTO brands (name, is_system)
VALUES
  ('Zara', true),
  ('H&M', true),
  ('Uniqlo', true),
  ('Mango', true),
  ('Bershka', true),
  ('Pull & Bear', true),
  ('Stradivarius', true),
  ('Massimo Dutti', true),
  ('COS', true),
  ('Arket', true),
  ('Weekday', true),
  ('Monki', true),
  ('Urban Outfitters', true),
  ('Forever 21', true),
  ('Topshop', true),
  ('ASOS', true),
  ('Shein', true),
  ('PrettyLittleThing', true),
  ('Boohoo', true),
  ('Missguided', true),
  ('Nike', true),
  ('Adidas', true),
  ('Puma', true),
  ('Reebok', true),
  ('New Balance', true),
  ('Under Armour', true),
  ('The North Face', true),
  ('Patagonia', true),
  ('Columbia', true),
  ('Lululemon', true),
  ('Levi''s', true),
  ('Wrangler', true),
  ('Lee', true),
  ('Tommy Hilfiger', true),
  ('Calvin Klein', true),
  ('Ralph Lauren', true),
  ('Lacoste', true),
  ('Gap', true),
  ('Banana Republic', true),
  ('Old Navy', true),
  ('Abercrombie & Fitch', true),
  ('Hollister', true),
  ('American Eagle', true),
  ('Aritzia', true),
  ('Brandy Melville', true),
  ('Reformation', true),
  ('Everlane', true),
  ('Sézane', true),
  ('Ganni', true),
  ('Sandro', true),
  ('Maje', true),
  ('Ba&sh', true),
  ('AllSaints', true),
  ('Diesel', true),
  ('Guess', true),
  ('Superdry', true),
  ('Jack & Jones', true),
  ('Only', true),
  ('Vero Moda', true),
  ('Reserved', true),
  ('C&A', true),
  ('Primark', true),
  ('Next', true),
  ('Marks & Spencer', true),
  ('Moncler', true),
  ('Canada Goose', true),
  ('Armani', true),
  ('Gucci', true),
  ('Prada', true),
  ('Chanel', true),
  ('Dior', true),
  ('Balenciaga', true),
  ('Saint Laurent', true),
  ('Hermès', true),
  ('Burberry', true),
  ('Coach', true),
  ('Michael Kors', true),
  ('Kate Spade', true),
  ('Tory Burch', true),
  ('Vivienne Westwood', true),
  ('Alexander McQueen', true),
  ('Off-White', true),
  ('Stone Island', true),
  ('Carhartt WIP', true),
  ('Dickies', true),
  ('Champion', true),
  ('Fila', true),
  ('Converse', true),
  ('Vans', true),
  ('Dr. Martens', true),
  ('Timberland', true),
  ('New Look', true),
  ('Zalando Essentials', true),
  ('House of Sunny', true),
  ('Marine Serre', true),
  ('Stella McCartney', true),
  ('Pangaia', true),
  ('Veja', true),
  ('Rains', true),
  ('Napapijri', true),
  ('Unknown', true)
ON CONFLICT (name) DO NOTHING;

